spring:
  application:
    name: neura-mcp-client
  ai:
    mcp:
      client:
        enabled: true
        name: my-mcp-client
        version: 1.0.0
        request-timeout: 30s
        type: SYNC
        sse:
          connections:
            timeplus-mcp-server:
              url: http://localhost:8081
    openai:
      api-key: ${OPENAI_KEY}
